name: Races
version: '${version}'
authors: [ LemonyPancakes ]

bootstrapper: me.lemonypancakes.races.bootstrap.Bootstrap
main: me.lemonypancakes.races.plugin.PaperPlugin

folia-supported: true
api-version: '1.21'
