name: Races
version: '${version}'
api-version: '1.21'
bootsrapper: me.lemonypancakes.races.bootstrap.Bootstrap
main: me.lemonypancakes.races.plugin.PaperPlugin
authors:
  - LemonyPancakes
folia-supported: true
